-- 0113_otp_login.sql — OTP login verification (ADR-0088): new-device second factor.
-- auth_otp_challenges: one short-lived login code per (user, device). The code is AES-256-GCM
--   encrypted (platform/encryption.ts, MFA_ENC_KEY — same at-rest scheme as TOTP secrets), NOT a
--   one-way hash: the resend rule re-delivers the SAME still-valid code (SMS economy), which a hash
--   cannot do. Verify = decrypt + timingSafeEqual; 5 attempts / 5-minute TTL bound the search space.
-- auth_trusted_devices: devices that have passed OTP once; trust slides on use (180 days, app-side).
-- roles.otp_login_required: per-role enforcement — FIELD_AGENT seeds OFF (the installed mobile fleet
--   has no OTP screen; ADR-0054). Flip it ON in role admin (no deploy) when the OTP-capable app ships.
-- Forward-only, idempotent. NOTE: the seed UPDATE re-applies on a re-run — do not edit this file
-- after ship if an admin has deliberately turned a listed role OFF.

CREATE TABLE IF NOT EXISTS auth_otp_challenges (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose        text NOT NULL DEFAULT 'LOGIN', -- only LOGIN today; text for future flows (ADR-0088)
  device_id      varchar(128),                  -- NULL = caller sent no deviceId (never trusted)
  code_encrypted text NOT NULL,
  expires_at     timestamptz NOT NULL,
  attempts       integer NOT NULL DEFAULT 0,
  send_count     integer NOT NULL DEFAULT 1,
  last_sent_at   timestamptz NOT NULL DEFAULT now(),
  sent_email     boolean NOT NULL DEFAULT false,
  sent_sms       boolean NOT NULL DEFAULT false,
  consumed_at    timestamptz,
  created_ip     inet,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_otp_challenges_user ON auth_otp_challenges (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS auth_trusted_devices (
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id    varchar(128) NOT NULL,
  trusted_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, device_id)
);

ALTER TABLE roles ADD COLUMN IF NOT EXISTS otp_login_required boolean NOT NULL DEFAULT false;

-- Office/web roles enforce immediately; FIELD_AGENT waits for the OTP-capable mobile release.
UPDATE roles SET otp_login_required = true
 WHERE code IN ('SUPER_ADMIN', 'MANAGER', 'TEAM_LEADER', 'BACKEND_USER', 'KYC_VERIFIER');
