import { logger } from '@crm2/logger';
import type { CaseReportContext } from '@crm2/sdk';

/**
 * CASE_REPORT → Excel (.xlsx) renderer (ADR-0041 S5 slice 5). A THREE-SHEET workbook built
 * programmatically via exceljs (already a v2 dep): (1) Case Summary — one row; (2) Per-Task Outcomes —
 * one row per verification task; (3) Photo Manifest — one row per field photo (type, GPS, frozen
 * address, capture-time, task, presigned URL). Photos are LISTED/linked, NOT embedded as binary
 * (file-bloat + cell-size limits — the PDF/Word renderers embed; the spreadsheet is a data export).
 *
 * ⭐ SECURITY: every free-text value flows through `csvSafe` — a leading =/+/-/@ is prefixed with a
 * single quote so Excel/Sheets never interprets a case field (an applicant name, a narrative) as a
 * FORMULA (CSV/spreadsheet formula-injection). exceljs's value API also XML-encodes content, so there
 * is no markup-injection sink; the formula guard is the spreadsheet-specific defense.
 */

const dash = (v: unknown): string => {
  const s = v == null ? '' : String(v).trim();
  return s === '' ? '' : s;
};
const fmtDate = (v: string | null): string => {
  if (!v) return '';
  const d = new Date(v);
  return Number.isNaN(d.getTime()) ? '' : d.toISOString().slice(0, 10);
};

/** Neutralize spreadsheet formula-injection: a cell starting =/+/-/@ (or a tab/CR that Excel trims to
 *  one of those) is prefixed with a single quote so it's treated as literal text, never a formula. */
export function csvSafe(value: unknown): string {
  const s = value == null ? '' : String(value);
  return /^[=+\-@\t\r]/.test(s) ? `'${s}` : s;
}

export async function renderCaseReportXlsx(ctx: CaseReportContext): Promise<Buffer> {
  const ExcelJS = (await import('exceljs')).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = 'CRM2';

  // 1) Case Summary — a single row of case identity + result + totals.
  const summary = wb.addWorksheet('Case Summary');
  summary.addRow(['Field', 'Value']);
  summary.getRow(1).font = { bold: true };
  const kv: [string, string][] = [
    ['Case Number', dash(ctx.case.caseNumber)],
    ['Client', dash(ctx.client.name)],
    ['Product', dash(ctx.product.name)],
    ['Customer', dash(ctx.case.customerName)],
    ['Phone', dash(ctx.case.customerPhone)],
    ['PAN', dash(ctx.case.panNumber)],
    ['Applicant Type', dash(ctx.case.applicantType)],
    ['Status', dash(ctx.case.status)],
    ['Case Result', dash(ctx.case.verificationOutcome)],
    ['Result Remark', dash(ctx.case.resultRemark)],
    ['Received', fmtDate(ctx.case.receivedDate)],
    ['Completed', fmtDate(ctx.case.completedDate)],
    ['TAT (days)', dash(ctx.case.tatDays)],
    ['Total Tasks', String(ctx.totals.totalTasks)],
    ['Completed Tasks', String(ctx.totals.completedTasks)],
    ['Positive', String(ctx.totals.positiveTasks)],
    ['Negative', String(ctx.totals.negativeTasks)],
    ['Refer', String(ctx.totals.referTasks)],
    ['Fraud', String(ctx.totals.fraudTasks)],
    ['Photos', String(ctx.totals.photoCount)],
    ['Generated', fmtDate(ctx.generation.generatedAt)],
    ['Generated By', dash(ctx.generation.generatedByName)],
  ];
  for (const [k, v] of kv) summary.addRow([k, csvSafe(v)]);
  summary.getColumn(1).width = 22;
  summary.getColumn(2).width = 48;

  // 2) Per-Task Outcomes — one row per verification task.
  const tasks = wb.addWorksheet('Per-Task Outcomes');
  const taskCols = [
    'Task Number',
    'Verification',
    'Applicant',
    'Address',
    'Outcome',
    'Remark',
    'Completed',
    'Photos',
  ];
  tasks.addRow(taskCols);
  tasks.getRow(1).font = { bold: true };
  for (const t of ctx.tasks) {
    tasks.addRow([
      csvSafe(t.taskNumber),
      csvSafe(t.unitName),
      csvSafe(t.applicantName),
      csvSafe(t.address),
      csvSafe(t.outcome ?? ''),
      csvSafe(t.remark ?? ''),
      fmtDate(t.completedAt),
      t.photos.length,
    ]);
  }
  taskCols.forEach((_, i) => (tasks.getColumn(i + 1).width = i === 3 ? 36 : 18));

  // 3) Photo Manifest — one row per field photo (linked, not embedded).
  const photos = wb.addWorksheet('Photo Manifest');
  const photoCols = [
    'Task Number',
    'Photo Type',
    'Latitude',
    'Longitude',
    'Accuracy (m)',
    'Address',
    'Captured',
    'URL',
  ];
  photos.addRow(photoCols);
  photos.getRow(1).font = { bold: true };
  for (const t of ctx.tasks) {
    for (const p of t.photos) {
      photos.addRow([
        csvSafe(t.taskNumber),
        csvSafe(p.photoType ?? ''),
        p.latitude ?? '',
        p.longitude ?? '',
        p.accuracy ?? '',
        csvSafe(p.reverseGeocodedAddress ?? ''),
        fmtDate(p.captureTime),
        // The presigned URL is server-issued + time-limited; it is plain text here (csvSafe-guarded),
        // NOT an Excel HYPERLINK() formula — a formula would re-open the injection surface.
        csvSafe(p.url),
      ]);
    }
  }
  photoCols.forEach((_, i) => (photos.getColumn(i + 1).width = i === 5 || i === 7 ? 40 : 16));

  const buf = Buffer.from(await wb.xlsx.writeBuffer());
  logger.info('xlsx: rendered case report', { caseId: ctx.case.id, bytes: buf.length });
  return buf;
}
